_wandb:
    value:
        cli_version: 0.18.6
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 50
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 50
                - 53
                - 55
                - 103
            "3":
                - 2
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.8.20
            "5": 0.18.6
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
